# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=secure-access-control-service

# ===============================
# MONGODB CONFIG
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/secure_access_db

# ===============================
# JWT CONFIG (custom)
# ===============================
jwt.secret=secret_key
jwt.expiration=86400000

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.project.security=DEBUG

# ===============================
# VALIDATION / ERROR
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always